### Create
 POST http://localhost:8080/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="turtle.jpg"
#Content-Disposition: form-data; name="file"; filename="test 02.mp4"

< C:\Users\allay\OneDrive\Рабочий стол\img\turtle.jpg
#< C:\Users\allay\OneDrive\Рабочий стол\img\test 02.mp4

### get image
GET http://localhost:8081/attach/open/08ea066b-8fe8-49d3-8adf-8a75d880e7e9.mp4



### get general
GET http://localhost:8081/attach/open_general/08ea066b-8fe8-49d3-8adf-8a75d880e7e9.mp4

###
GET http://localhost:8081/attach/open/test_kun_uz.jpg


### download
GET http://localhost:8080/attach/download/7da99574-74a2-448b-90fe-e32aae149854.jpg

### delete
DELETE http://localhost:8080/attach/adm/delete/7da99574-74a2-448b-90fe-e32aae149854.jpg
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcwNzMyNzYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDcxNTk2NzYsImlzcyI6Ikt1blV6VGVzdCJ9.LvWLSV92N1vL1ksCvknCIPQtH0i3PJIWPRWrDQ3FS9SWt0w6_8QF6NdA3A8jNTvPUorYODSN_i3m4Za17irOsg