### Login  1
POST localhost:8080/auth/login
Accept-Language: UZ
Content-Type: application/json
#user

//{
//  "email": "allayarovshahzodbekz@gmail.com",
//  "password": "User1234@"
//}
//{
//  "email": "Adminceek1234@gmail.com",
//  "password": "User1234@"
//}

{
  "email": "user@gmail.com",
  "password": "$1User1$"
}




####Registration
POST localhost:8080/auth/registration
Content-Type: application/json

{

  "name": "Shahzodbek",
  "surname": "Aliyev",
  "email": "allayarovshahzodbekz@gmail.com",
  "password": "User1234@"
}

###Verification By email
GET localhost:8080/auth/verification/email/eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTA0ODc0NTQsImlkIjoyLCJleHAiOjE3MTA0ODc3NTQsImlzcyI6IkUtY29tbWVyY2UifQ.btrTiYd62-uxQl40Py6bKnopQsjEtjGVpjmQk6cO8kYwJHbvDLo2lLj_mopr-XnZ1s4a2oD1Lhm0ah7NmWyJ2g



