###create
POST http://localhost:8080/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTA1ODg4OTMsImVtYWlsIjoiQWRtaW5jZWVrMTIzNEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTcxMDY3NTI5MywiaXNzIjoiS3VuVXpUZXN0In0.PV2Xnoip0KSGRzk8YE8ufXlEaEmGVXmp82_4hpw8rAh6JQtDiOHVLuHnmLdSKombdavx2G7_TUrHYbaA2IdghA

{
  "name": "Mi",
  "parentId": 2
}

### update
PUT http://localhost:8080/category/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTA1ODg4OTMsImVtYWlsIjoiQWRtaW5jZWVrMTIzNEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTcxMDY3NTI5MywiaXNzIjoiS3VuVXpUZXN0In0.PV2Xnoip0KSGRzk8YE8ufXlEaEmGVXmp82_4hpw8rAh6JQtDiOHVLuHnmLdSKombdavx2G7_TUrHYbaA2IdghA

{
  "name": "Iphone",
  "parentId": 2
}


### delete
DELETE http://localhost:8080/category/1
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTA1ODg4OTMsImVtYWlsIjoiQWRtaW5jZWVrMTIzNEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTcxMDY3NTI5MywiaXNzIjoiS3VuVXpUZXN0In0.PV2Xnoip0KSGRzk8YE8ufXlEaEmGVXmp82_4hpw8rAh6JQtDiOHVLuHnmLdSKombdavx2G7_TUrHYbaA2IdghA

### List
GET http://localhost:8080/category/list

### list by parent id
GET http://localhost:8080/category/parent/1

### search
GET http://localhost:8080/category/categories/search?query=ele



