### create
POST http://localhost:8080/store
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTA5MTgyMDcsImVtYWlsIjoiQWRtaW5jZWVrMTIzNEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTcxMjk5MTgwNywiaXNzIjoiS3VuVXpUZXN0In0.KQgfmNcsSmvnq1K19AitDvPl2GkgdV3-UE6labPaZC7LJwxzpCFlqktARc8yfP4jOuclJyDn2IQNAgbXGDQRmQ

{
  "name": "Button",
  "profileId":4,
  "attachId": "71d54059-69ad-4023-bd66-ec640d29707a",
  "descriptionUz": "Erkaklar kiyimi uz",
  "descriptionRu": "Erkaklar kiyimi ru",
  "descriptionEn": "Erkaklar kiyimi en"
}


### UPDATE
PUT http://localhost:8080/store/1
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTA3NTYyMTUsImVtYWlsIjoidXNlcjEyMjNAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfU0VMTEVSIiwiZXhwIjoxNzEwODQyNjE1LCJpc3MiOiJLdW5VelRlc3QifQ.6A4Bil879fdTm-TYCq2NBLbTjh_Kebpouu2xfan79gsHTsIuZNrMHnnOvBGy3H0PTlSR7wUckRpQYzeZjFw6Sw
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTA5MjAxMjMsImVtYWlsIjoidXNlckBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9TRUxMRVIiLCJleHAiOjE3MTI5OTM3MjMsImlzcyI6Ikt1blV6VGVzdCJ9.ub-VrEJHDiR6KKSOyUbySaxyoBoDeOzuNUKq8IUbFUH7d8jcXKVvdDbB6oylc_x05WSo-ibIE9lLrrAA4l9vVg

{
  "attachId": "e50dc317-2618-4358-b9b4-1fcf05c6c0c5"
}



### pagination by ADMIN
GET http://localhost:8080/store/getByPagination
Accept-Language: RU
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTA5MTgyMDcsImVtYWlsIjoiQWRtaW5jZWVrMTIzNEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTcxMjk5MTgwNywiaXNzIjoiS3VuVXpUZXN0In0.KQgfmNcsSmvnq1K19AitDvPl2GkgdV3-UE6labPaZC7LJwxzpCFlqktARc8yfP4jOuclJyDn2IQNAgbXGDQRmQ

###
GET http://localhost:8080/store/getList
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTA5MTgyMDcsImVtYWlsIjoiQWRtaW5jZWVrMTIzNEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTcxMjk5MTgwNywiaXNzIjoiS3VuVXpUZXN0In0.KQgfmNcsSmvnq1K19AitDvPl2GkgdV3-UE6labPaZC7LJwxzpCFlqktARc8yfP4jOuclJyDn2IQNAgbXGDQRmQ

###
GET http://localhost:8080/store/get-by-profile?profileId=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTA5MTgyMDcsImVtYWlsIjoiQWRtaW5jZWVrMTIzNEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTcxMjk5MTgwNywiaXNzIjoiS3VuVXpUZXN0In0.KQgfmNcsSmvnq1K19AitDvPl2GkgdV3-UE6labPaZC7LJwxzpCFlqktARc8yfP4jOuclJyDn2IQNAgbXGDQRmQ


